package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Elements;
import org.vamdc.BasecolTest.dao.EnergyTables;

/**
 * Class _CaseByCase was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CaseByCase extends CayenneDataObject {

    public static final String ID_CASE_PROPERTY = "idCase";
    public static final String ID_ELEMENT_PROPERTY = "idElement";
    public static final String ID_ENERGY_TABLE_PROPERTY = "idEnergyTable";
    public static final String TO_ELEMENTS_PROPERTY = "toElements";
    public static final String TO_ENERGY_TABLES_PROPERTY = "toEnergyTables";

    public static final String ID_CASE_PK_COLUMN = "idCase";
    public static final String ID_ELEMENT_PK_COLUMN = "idElement";

    public void setIdCase(Short idCase) {
        writeProperty(ID_CASE_PROPERTY, idCase);
    }
    public Short getIdCase() {
        return (Short)readProperty(ID_CASE_PROPERTY);
    }

    public void setIdElement(Long idElement) {
        writeProperty(ID_ELEMENT_PROPERTY, idElement);
    }
    public Long getIdElement() {
        return (Long)readProperty(ID_ELEMENT_PROPERTY);
    }

    public void setIdEnergyTable(Long idEnergyTable) {
        writeProperty(ID_ENERGY_TABLE_PROPERTY, idEnergyTable);
    }
    public Long getIdEnergyTable() {
        return (Long)readProperty(ID_ENERGY_TABLE_PROPERTY);
    }

    public void setToElements(Elements toElements) {
        setToOneTarget(TO_ELEMENTS_PROPERTY, toElements, true);
    }

    public Elements getToElements() {
        return (Elements)readProperty(TO_ELEMENTS_PROPERTY);
    }


    public void setToEnergyTables(EnergyTables toEnergyTables) {
        setToOneTarget(TO_ENERGY_TABLES_PROPERTY, toEnergyTables, true);
    }

    public EnergyTables getToEnergyTables() {
        return (EnergyTables)readProperty(TO_ENERGY_TABLES_PROPERTY);
    }


}
