package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Members;

/**
 * Class _CollaborationGroups was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CollaborationGroups extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String ID_COL_GROUP_PROPERTY = "idColGroup";
    public static final String NAME_PROPERTY = "name";
    public static final String WEBSITE_PROPERTY = "website";
    public static final String MEMBERSS_PROPERTY = "memberss";

    public static final String ID_COL_GROUP_PK_COLUMN = "idColGroup";

    public void setAddress(String address) {
        writeProperty(ADDRESS_PROPERTY, address);
    }
    public String getAddress() {
        return (String)readProperty(ADDRESS_PROPERTY);
    }

    public void setIdColGroup(Long idColGroup) {
        writeProperty(ID_COL_GROUP_PROPERTY, idColGroup);
    }
    public Long getIdColGroup() {
        return (Long)readProperty(ID_COL_GROUP_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setWebsite(String website) {
        writeProperty(WEBSITE_PROPERTY, website);
    }
    public String getWebsite() {
        return (String)readProperty(WEBSITE_PROPERTY);
    }

    public void addToMemberss(Members obj) {
        addToManyTarget(MEMBERSS_PROPERTY, obj, true);
    }
    public void removeFromMemberss(Members obj) {
        removeToManyTarget(MEMBERSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Members> getMemberss() {
        return (List<Members>)readProperty(MEMBERSS_PROPERTY);
    }


}
