package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Collisions;

/**
 * Class _Contributors was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contributors extends CayenneDataObject {

    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String ID_CONTRIBUTOR_PROPERTY = "idContributor";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String MAIL_PROPERTY = "mail";
    public static final String COLLISIONSS_PROPERTY = "collisionss";

    public static final String ID_CONTRIBUTOR_PK_COLUMN = "idContributor";

    public void setFirstName(String firstName) {
        writeProperty(FIRST_NAME_PROPERTY, firstName);
    }
    public String getFirstName() {
        return (String)readProperty(FIRST_NAME_PROPERTY);
    }

    public void setIdContributor(Long idContributor) {
        writeProperty(ID_CONTRIBUTOR_PROPERTY, idContributor);
    }
    public Long getIdContributor() {
        return (Long)readProperty(ID_CONTRIBUTOR_PROPERTY);
    }

    public void setLastName(String lastName) {
        writeProperty(LAST_NAME_PROPERTY, lastName);
    }
    public String getLastName() {
        return (String)readProperty(LAST_NAME_PROPERTY);
    }

    public void setMail(String mail) {
        writeProperty(MAIL_PROPERTY, mail);
    }
    public String getMail() {
        return (String)readProperty(MAIL_PROPERTY);
    }

    public void addToCollisionss(Collisions obj) {
        addToManyTarget(COLLISIONSS_PROPERTY, obj, true);
    }
    public void removeFromCollisionss(Collisions obj) {
        removeToManyTarget(COLLISIONSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Collisions> getCollisionss() {
        return (List<Collisions>)readProperty(COLLISIONSS_PROPERTY);
    }


}
