package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.CaseByCase;
import org.vamdc.BasecolTest.dao.ElementTypes;
import org.vamdc.BasecolTest.dao.EnergyTables;
import org.vamdc.BasecolTest.dao.MoleculeAtoms;
import org.vamdc.BasecolTest.dao.MoleculeBonds;
import org.vamdc.BasecolTest.dao.PartitionFunctions;
import org.vamdc.BasecolTest.dao.StatusCurrentWorks;
import org.vamdc.BasecolTest.dao.StatusNeeds;

/**
 * Class _Elements was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Elements extends CayenneDataObject {

    public static final String CHARGE_PROPERTY = "charge";
    public static final String DESIGNATION_PROPERTY = "designation";
    public static final String ID_ELEMENT_PROPERTY = "idElement";
    public static final String ID_ELEMENT_TYPE_PROPERTY = "idElementType";
    public static final String INCHI_PROPERTY = "inchi";
    public static final String INCHI_KEY_PROPERTY = "inchiKey";
    public static final String LATEX_PROPERTY = "latex";
    public static final String MOLECULAR_CONSTANT_PROPERTY = "molecularConstant";
    public static final String MOLECULAR_MASS_PROPERTY = "molecularMass";
    public static final String STOICHIOMETRIC_FORMULA_PROPERTY = "stoichiometricFormula";
    public static final String TYPE_OF_MOLECULE_PROPERTY = "typeOfMolecule";
    public static final String CASEBYCASES_PROPERTY = "casebycases";
    public static final String ENERGYTABLESES_PROPERTY = "energytableses";
    public static final String MOLECULEATOMSS_PROPERTY = "moleculeatomss";
    public static final String MOLECULEBONDSS_PROPERTY = "moleculebondss";
    public static final String PARTITIONFUNCTIONSS_PROPERTY = "partitionfunctionss";
    public static final String STATUS_CURRENTWORKSS_PROPERTY = "statusCurrentworkss";
    public static final String STATUS_CURRENTWORKSS1_PROPERTY = "statusCurrentworkss1";
    public static final String STATUS_NEEDSS_PROPERTY = "statusNeedss";
    public static final String STATUS_NEEDSS1_PROPERTY = "statusNeedss1";
    public static final String TO_ELEMENT_TYPES_PROPERTY = "toElementTypes";

    public static final String ID_ELEMENT_PK_COLUMN = "idElement";

    public void setCharge(Short charge) {
        writeProperty(CHARGE_PROPERTY, charge);
    }
    public Short getCharge() {
        return (Short)readProperty(CHARGE_PROPERTY);
    }

    public void setDesignation(String designation) {
        writeProperty(DESIGNATION_PROPERTY, designation);
    }
    public String getDesignation() {
        return (String)readProperty(DESIGNATION_PROPERTY);
    }

    public void setIdElement(Long idElement) {
        writeProperty(ID_ELEMENT_PROPERTY, idElement);
    }
    public Long getIdElement() {
        return (Long)readProperty(ID_ELEMENT_PROPERTY);
    }

    public void setIdElementType(Byte idElementType) {
        writeProperty(ID_ELEMENT_TYPE_PROPERTY, idElementType);
    }
    public Byte getIdElementType() {
        return (Byte)readProperty(ID_ELEMENT_TYPE_PROPERTY);
    }

    public void setInchi(String inchi) {
        writeProperty(INCHI_PROPERTY, inchi);
    }
    public String getInchi() {
        return (String)readProperty(INCHI_PROPERTY);
    }

    public void setInchiKey(String inchiKey) {
        writeProperty(INCHI_KEY_PROPERTY, inchiKey);
    }
    public String getInchiKey() {
        return (String)readProperty(INCHI_KEY_PROPERTY);
    }

    public void setLatex(String latex) {
        writeProperty(LATEX_PROPERTY, latex);
    }
    public String getLatex() {
        return (String)readProperty(LATEX_PROPERTY);
    }

    public void setMolecularConstant(Double molecularConstant) {
        writeProperty(MOLECULAR_CONSTANT_PROPERTY, molecularConstant);
    }
    public Double getMolecularConstant() {
        return (Double)readProperty(MOLECULAR_CONSTANT_PROPERTY);
    }

    public void setMolecularMass(Double molecularMass) {
        writeProperty(MOLECULAR_MASS_PROPERTY, molecularMass);
    }
    public Double getMolecularMass() {
        return (Double)readProperty(MOLECULAR_MASS_PROPERTY);
    }

    public void setStoichiometricFormula(String stoichiometricFormula) {
        writeProperty(STOICHIOMETRIC_FORMULA_PROPERTY, stoichiometricFormula);
    }
    public String getStoichiometricFormula() {
        return (String)readProperty(STOICHIOMETRIC_FORMULA_PROPERTY);
    }

    public void setTypeOfMolecule(String typeOfMolecule) {
        writeProperty(TYPE_OF_MOLECULE_PROPERTY, typeOfMolecule);
    }
    public String getTypeOfMolecule() {
        return (String)readProperty(TYPE_OF_MOLECULE_PROPERTY);
    }

    public void addToCasebycases(CaseByCase obj) {
        addToManyTarget(CASEBYCASES_PROPERTY, obj, true);
    }
    public void removeFromCasebycases(CaseByCase obj) {
        removeToManyTarget(CASEBYCASES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CaseByCase> getCasebycases() {
        return (List<CaseByCase>)readProperty(CASEBYCASES_PROPERTY);
    }


    public void addToEnergytableses(EnergyTables obj) {
        addToManyTarget(ENERGYTABLESES_PROPERTY, obj, true);
    }
    public void removeFromEnergytableses(EnergyTables obj) {
        removeToManyTarget(ENERGYTABLESES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EnergyTables> getEnergytableses() {
        return (List<EnergyTables>)readProperty(ENERGYTABLESES_PROPERTY);
    }


    public void addToMoleculeatomss(MoleculeAtoms obj) {
        addToManyTarget(MOLECULEATOMSS_PROPERTY, obj, true);
    }
    public void removeFromMoleculeatomss(MoleculeAtoms obj) {
        removeToManyTarget(MOLECULEATOMSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MoleculeAtoms> getMoleculeatomss() {
        return (List<MoleculeAtoms>)readProperty(MOLECULEATOMSS_PROPERTY);
    }


    public void addToMoleculebondss(MoleculeBonds obj) {
        addToManyTarget(MOLECULEBONDSS_PROPERTY, obj, true);
    }
    public void removeFromMoleculebondss(MoleculeBonds obj) {
        removeToManyTarget(MOLECULEBONDSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MoleculeBonds> getMoleculebondss() {
        return (List<MoleculeBonds>)readProperty(MOLECULEBONDSS_PROPERTY);
    }


    public void addToPartitionfunctionss(PartitionFunctions obj) {
        addToManyTarget(PARTITIONFUNCTIONSS_PROPERTY, obj, true);
    }
    public void removeFromPartitionfunctionss(PartitionFunctions obj) {
        removeToManyTarget(PARTITIONFUNCTIONSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PartitionFunctions> getPartitionfunctionss() {
        return (List<PartitionFunctions>)readProperty(PARTITIONFUNCTIONSS_PROPERTY);
    }


    public void addToStatusCurrentworkss(StatusCurrentWorks obj) {
        addToManyTarget(STATUS_CURRENTWORKSS_PROPERTY, obj, true);
    }
    public void removeFromStatusCurrentworkss(StatusCurrentWorks obj) {
        removeToManyTarget(STATUS_CURRENTWORKSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<StatusCurrentWorks> getStatusCurrentworkss() {
        return (List<StatusCurrentWorks>)readProperty(STATUS_CURRENTWORKSS_PROPERTY);
    }


    public void addToStatusCurrentworkss1(StatusCurrentWorks obj) {
        addToManyTarget(STATUS_CURRENTWORKSS1_PROPERTY, obj, true);
    }
    public void removeFromStatusCurrentworkss1(StatusCurrentWorks obj) {
        removeToManyTarget(STATUS_CURRENTWORKSS1_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<StatusCurrentWorks> getStatusCurrentworkss1() {
        return (List<StatusCurrentWorks>)readProperty(STATUS_CURRENTWORKSS1_PROPERTY);
    }


    public void addToStatusNeedss(StatusNeeds obj) {
        addToManyTarget(STATUS_NEEDSS_PROPERTY, obj, true);
    }
    public void removeFromStatusNeedss(StatusNeeds obj) {
        removeToManyTarget(STATUS_NEEDSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<StatusNeeds> getStatusNeedss() {
        return (List<StatusNeeds>)readProperty(STATUS_NEEDSS_PROPERTY);
    }


    public void addToStatusNeedss1(StatusNeeds obj) {
        addToManyTarget(STATUS_NEEDSS1_PROPERTY, obj, true);
    }
    public void removeFromStatusNeedss1(StatusNeeds obj) {
        removeToManyTarget(STATUS_NEEDSS1_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<StatusNeeds> getStatusNeedss1() {
        return (List<StatusNeeds>)readProperty(STATUS_NEEDSS1_PROPERTY);
    }


    public void setToElementTypes(ElementTypes toElementTypes) {
        setToOneTarget(TO_ELEMENT_TYPES_PROPERTY, toElementTypes, true);
    }

    public ElementTypes getToElementTypes() {
        return (ElementTypes)readProperty(TO_ELEMENT_TYPES_PROPERTY);
    }


}
