package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Elements;

/**
 * Class _ElementTypes was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ElementTypes extends CayenneDataObject {

    public static final String DESIGNATION_PROPERTY = "designation";
    public static final String ID_ELEMENT_TYPE_PROPERTY = "idElementType";
    public static final String ELEMENTSS_PROPERTY = "elementss";

    public static final String ID_ELEMENT_TYPE_PK_COLUMN = "idElementType";

    public void setDesignation(String designation) {
        writeProperty(DESIGNATION_PROPERTY, designation);
    }
    public String getDesignation() {
        return (String)readProperty(DESIGNATION_PROPERTY);
    }

    public void setIdElementType(Short idElementType) {
        writeProperty(ID_ELEMENT_TYPE_PROPERTY, idElementType);
    }
    public Short getIdElementType() {
        return (Short)readProperty(ID_ELEMENT_TYPE_PROPERTY);
    }

    public void addToElementss(Elements obj) {
        addToManyTarget(ELEMENTSS_PROPERTY, obj, true);
    }
    public void removeFromElementss(Elements obj) {
        removeToManyTarget(ELEMENTSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Elements> getElementss() {
        return (List<Elements>)readProperty(ELEMENTSS_PROPERTY);
    }


}
