package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.EnergyTablesLevels;
import org.vamdc.BasecolTest.dao.QuantumNumbers;

/**
 * Class _EnergyTablesLevelsQuantumNumbers was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EnergyTablesLevelsQuantumNumbers extends CayenneDataObject {

    public static final String ID_LEVEL_PROPERTY = "idLevel";
    public static final String ID_QUANTUM_NUMBER_PROPERTY = "idQuantumNumber";
    public static final String STRING_VALUE_PROPERTY = "stringValue";
    public static final String VALUE_PROPERTY = "value";
    public static final String TO_ENERGY_TABLES_LEVELS_PROPERTY = "toEnergyTablesLevels";
    public static final String TO_QUANTUM_NUMBERS_PROPERTY = "toQuantumNumbers";

    public static final String ID_LEVEL_PK_COLUMN = "idLevel";
    public static final String ID_QUANTUM_NUMBER_PK_COLUMN = "idQuantumNumber";

    public void setIdLevel(Long idLevel) {
        writeProperty(ID_LEVEL_PROPERTY, idLevel);
    }
    public Long getIdLevel() {
        return (Long)readProperty(ID_LEVEL_PROPERTY);
    }

    public void setIdQuantumNumber(Long idQuantumNumber) {
        writeProperty(ID_QUANTUM_NUMBER_PROPERTY, idQuantumNumber);
    }
    public Long getIdQuantumNumber() {
        return (Long)readProperty(ID_QUANTUM_NUMBER_PROPERTY);
    }

    public void setStringValue(String stringValue) {
        writeProperty(STRING_VALUE_PROPERTY, stringValue);
    }
    public String getStringValue() {
        return (String)readProperty(STRING_VALUE_PROPERTY);
    }

    public void setValue(Double value) {
        writeProperty(VALUE_PROPERTY, value);
    }
    public Double getValue() {
        return (Double)readProperty(VALUE_PROPERTY);
    }

    public void setToEnergyTablesLevels(EnergyTablesLevels toEnergyTablesLevels) {
        setToOneTarget(TO_ENERGY_TABLES_LEVELS_PROPERTY, toEnergyTablesLevels, true);
    }

    public EnergyTablesLevels getToEnergyTablesLevels() {
        return (EnergyTablesLevels)readProperty(TO_ENERGY_TABLES_LEVELS_PROPERTY);
    }


    public void setToQuantumNumbers(QuantumNumbers toQuantumNumbers) {
        setToOneTarget(TO_QUANTUM_NUMBERS_PROPERTY, toQuantumNumbers, true);
    }

    public QuantumNumbers getToQuantumNumbers() {
        return (QuantumNumbers)readProperty(TO_QUANTUM_NUMBERS_PROPERTY);
    }


}
