package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.EnergyTables;
import org.vamdc.BasecolTest.dao.Processus;

/**
 * Class _EnergyTablesProcessus was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EnergyTablesProcessus extends CayenneDataObject {

    public static final String ID_ENERGY_TABLE_PROPERTY = "idEnergyTable";
    public static final String ID_PROCESSUS_PROPERTY = "idProcessus";
    public static final String TO_ENERGY_TABLES_PROPERTY = "toEnergyTables";
    public static final String TO_PROCESSUS_PROPERTY = "toProcessus";

    public static final String ID_ENERGY_TABLE_PK_COLUMN = "idEnergyTable";
    public static final String ID_PROCESSUS_PK_COLUMN = "idProcessus";

    public void setIdEnergyTable(Long idEnergyTable) {
        writeProperty(ID_ENERGY_TABLE_PROPERTY, idEnergyTable);
    }
    public Long getIdEnergyTable() {
        return (Long)readProperty(ID_ENERGY_TABLE_PROPERTY);
    }

    public void setIdProcessus(Short idProcessus) {
        writeProperty(ID_PROCESSUS_PROPERTY, idProcessus);
    }
    public Short getIdProcessus() {
        return (Short)readProperty(ID_PROCESSUS_PROPERTY);
    }

    public void setToEnergyTables(EnergyTables toEnergyTables) {
        setToOneTarget(TO_ENERGY_TABLES_PROPERTY, toEnergyTables, true);
    }

    public EnergyTables getToEnergyTables() {
        return (EnergyTables)readProperty(TO_ENERGY_TABLES_PROPERTY);
    }


    public void setToProcessus(Processus toProcessus) {
        setToOneTarget(TO_PROCESSUS_PROPERTY, toProcessus, true);
    }

    public Processus getToProcessus() {
        return (Processus)readProperty(TO_PROCESSUS_PROPERTY);
    }


}
