package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.EnergyTables;
import org.vamdc.BasecolTest.dao.EnergyTablesLevelsQuantumNumbers;
import org.vamdc.BasecolTest.dao.ForeignValues;
import org.vamdc.BasecolTest.dao.LevelGroups;
import org.vamdc.BasecolTest.dao.MatchedEnergyTablesLevels;

/**
 * Class _EnergyTablesLevels was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EnergyTablesLevels extends CayenneDataObject {

    public static final String DEGENERACY_PROPERTY = "degeneracy";
    public static final String ENERGY_PROPERTY = "energy";
    public static final String ID_LEVEL_PROPERTY = "idLevel";
    public static final String LEVEL_PROPERTY = "level";
    public static final String ENERGYTABLES_LEVELS_QUANTUMNUMBERSS_PROPERTY = "energytablesLevelsQuantumnumberss";
    public static final String FOREIGNVALUESES_PROPERTY = "foreignvalueses";
    public static final String FOREIGNVALUESES1_PROPERTY = "foreignvalueses1";
    public static final String LEVELGROUPSS_PROPERTY = "levelgroupss";
    public static final String LEVELGROUPSS1_PROPERTY = "levelgroupss1";
    public static final String LEVELGROUPSS2_PROPERTY = "levelgroupss2";
    public static final String LEVELGROUPSS3_PROPERTY = "levelgroupss3";
    public static final String MATCHEDENERGYTABLES_LEVELSS_PROPERTY = "matchedenergytablesLevelss";
    public static final String TO_ENERGY_TABLES_PROPERTY = "toEnergyTables";

    public static final String ID_LEVEL_PK_COLUMN = "idLevel";

    public void setDegeneracy(Integer degeneracy) {
        writeProperty(DEGENERACY_PROPERTY, degeneracy);
    }
    public Integer getDegeneracy() {
        return (Integer)readProperty(DEGENERACY_PROPERTY);
    }

    public void setEnergy(Double energy) {
        writeProperty(ENERGY_PROPERTY, energy);
    }
    public Double getEnergy() {
        return (Double)readProperty(ENERGY_PROPERTY);
    }

    public void setIdLevel(Long idLevel) {
        writeProperty(ID_LEVEL_PROPERTY, idLevel);
    }
    public Long getIdLevel() {
        return (Long)readProperty(ID_LEVEL_PROPERTY);
    }

    public void setLevel(Short level) {
        writeProperty(LEVEL_PROPERTY, level);
    }
    public Short getLevel() {
        return (Short)readProperty(LEVEL_PROPERTY);
    }

    public void addToEnergytablesLevelsQuantumnumberss(EnergyTablesLevelsQuantumNumbers obj) {
        addToManyTarget(ENERGYTABLES_LEVELS_QUANTUMNUMBERSS_PROPERTY, obj, true);
    }
    public void removeFromEnergytablesLevelsQuantumnumberss(EnergyTablesLevelsQuantumNumbers obj) {
        removeToManyTarget(ENERGYTABLES_LEVELS_QUANTUMNUMBERSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EnergyTablesLevelsQuantumNumbers> getEnergytablesLevelsQuantumnumberss() {
        return (List<EnergyTablesLevelsQuantumNumbers>)readProperty(ENERGYTABLES_LEVELS_QUANTUMNUMBERSS_PROPERTY);
    }


    public void addToForeignvalueses(ForeignValues obj) {
        addToManyTarget(FOREIGNVALUESES_PROPERTY, obj, true);
    }
    public void removeFromForeignvalueses(ForeignValues obj) {
        removeToManyTarget(FOREIGNVALUESES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ForeignValues> getForeignvalueses() {
        return (List<ForeignValues>)readProperty(FOREIGNVALUESES_PROPERTY);
    }


    public void addToForeignvalueses1(ForeignValues obj) {
        addToManyTarget(FOREIGNVALUESES1_PROPERTY, obj, true);
    }
    public void removeFromForeignvalueses1(ForeignValues obj) {
        removeToManyTarget(FOREIGNVALUESES1_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ForeignValues> getForeignvalueses1() {
        return (List<ForeignValues>)readProperty(FOREIGNVALUESES1_PROPERTY);
    }


    public void addToLevelgroupss(LevelGroups obj) {
        addToManyTarget(LEVELGROUPSS_PROPERTY, obj, true);
    }
    public void removeFromLevelgroupss(LevelGroups obj) {
        removeToManyTarget(LEVELGROUPSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<LevelGroups> getLevelgroupss() {
        return (List<LevelGroups>)readProperty(LEVELGROUPSS_PROPERTY);
    }


    public void addToLevelgroupss1(LevelGroups obj) {
        addToManyTarget(LEVELGROUPSS1_PROPERTY, obj, true);
    }
    public void removeFromLevelgroupss1(LevelGroups obj) {
        removeToManyTarget(LEVELGROUPSS1_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<LevelGroups> getLevelgroupss1() {
        return (List<LevelGroups>)readProperty(LEVELGROUPSS1_PROPERTY);
    }


    public void addToLevelgroupss2(LevelGroups obj) {
        addToManyTarget(LEVELGROUPSS2_PROPERTY, obj, true);
    }
    public void removeFromLevelgroupss2(LevelGroups obj) {
        removeToManyTarget(LEVELGROUPSS2_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<LevelGroups> getLevelgroupss2() {
        return (List<LevelGroups>)readProperty(LEVELGROUPSS2_PROPERTY);
    }


    public void addToLevelgroupss3(LevelGroups obj) {
        addToManyTarget(LEVELGROUPSS3_PROPERTY, obj, true);
    }
    public void removeFromLevelgroupss3(LevelGroups obj) {
        removeToManyTarget(LEVELGROUPSS3_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<LevelGroups> getLevelgroupss3() {
        return (List<LevelGroups>)readProperty(LEVELGROUPSS3_PROPERTY);
    }


    public void addToMatchedenergytablesLevelss(MatchedEnergyTablesLevels obj) {
        addToManyTarget(MATCHEDENERGYTABLES_LEVELSS_PROPERTY, obj, true);
    }
    public void removeFromMatchedenergytablesLevelss(MatchedEnergyTablesLevels obj) {
        removeToManyTarget(MATCHEDENERGYTABLES_LEVELSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MatchedEnergyTablesLevels> getMatchedenergytablesLevelss() {
        return (List<MatchedEnergyTablesLevels>)readProperty(MATCHEDENERGYTABLES_LEVELSS_PROPERTY);
    }


    public void setToEnergyTables(EnergyTables toEnergyTables) {
        setToOneTarget(TO_ENERGY_TABLES_PROPERTY, toEnergyTables, true);
    }

    public EnergyTables getToEnergyTables() {
        return (EnergyTables)readProperty(TO_ENERGY_TABLES_PROPERTY);
    }


}
