package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.EnergyTables;
import org.vamdc.BasecolTest.dao.QuantumNumbers;

/**
 * Class _EnergyTablesQuantumNumbers was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _EnergyTablesQuantumNumbers extends CayenneDataObject {

    public static final String ID_ENERGY_TABLE_PROPERTY = "idEnergyTable";
    public static final String ID_QUANTUM_NUMBER_PROPERTY = "idQuantumNumber";
    public static final String POSITION_PROPERTY = "position";
    public static final String TO_ENERGY_TABLES_PROPERTY = "toEnergyTables";
    public static final String TO_QUANTUM_NUMBERS_PROPERTY = "toQuantumNumbers";

    public static final String ID_ENERGY_TABLE_PK_COLUMN = "idEnergyTable";
    public static final String ID_QUANTUM_NUMBER_PK_COLUMN = "idQuantumNumber";

    public void setIdEnergyTable(Long idEnergyTable) {
        writeProperty(ID_ENERGY_TABLE_PROPERTY, idEnergyTable);
    }
    public Long getIdEnergyTable() {
        return (Long)readProperty(ID_ENERGY_TABLE_PROPERTY);
    }

    public void setIdQuantumNumber(Long idQuantumNumber) {
        writeProperty(ID_QUANTUM_NUMBER_PROPERTY, idQuantumNumber);
    }
    public Long getIdQuantumNumber() {
        return (Long)readProperty(ID_QUANTUM_NUMBER_PROPERTY);
    }

    public void setPosition(Short position) {
        writeProperty(POSITION_PROPERTY, position);
    }
    public Short getPosition() {
        return (Short)readProperty(POSITION_PROPERTY);
    }

    public void setToEnergyTables(EnergyTables toEnergyTables) {
        setToOneTarget(TO_ENERGY_TABLES_PROPERTY, toEnergyTables, true);
    }

    public EnergyTables getToEnergyTables() {
        return (EnergyTables)readProperty(TO_ENERGY_TABLES_PROPERTY);
    }


    public void setToQuantumNumbers(QuantumNumbers toQuantumNumbers) {
        setToOneTarget(TO_QUANTUM_NUMBERS_PROPERTY, toQuantumNumbers, true);
    }

    public QuantumNumbers getToQuantumNumbers() {
        return (QuantumNumbers)readProperty(TO_QUANTUM_NUMBERS_PROPERTY);
    }


}
