package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Fits;

/**
 * Class _FitEquations was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _FitEquations extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String DESIGNATION_PROPERTY = "designation";
    public static final String ID_FIT_EQUATION_PROPERTY = "idFitEquation";
    public static final String PROCESSING_PROPERTY = "processing";
    public static final String FITSS_PROPERTY = "fitss";

    public static final String ID_FIT_EQUATION_PK_COLUMN = "idFitEquation";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setDesignation(String designation) {
        writeProperty(DESIGNATION_PROPERTY, designation);
    }
    public String getDesignation() {
        return (String)readProperty(DESIGNATION_PROPERTY);
    }

    public void setIdFitEquation(Short idFitEquation) {
        writeProperty(ID_FIT_EQUATION_PROPERTY, idFitEquation);
    }
    public Short getIdFitEquation() {
        return (Short)readProperty(ID_FIT_EQUATION_PROPERTY);
    }

    public void setProcessing(String processing) {
        writeProperty(PROCESSING_PROPERTY, processing);
    }
    public String getProcessing() {
        return (String)readProperty(PROCESSING_PROPERTY);
    }

    public void addToFitss(Fits obj) {
        addToManyTarget(FITSS_PROPERTY, obj, true);
    }
    public void removeFromFitss(Fits obj) {
        removeToManyTarget(FITSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Fits> getFitss() {
        return (List<Fits>)readProperty(FITSS_PROPERTY);
    }


}
