package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.ForeignValues;
import org.vamdc.BasecolTest.dao.ForeignValuesSetsCollisions;
import org.vamdc.BasecolTest.dao.RefsMatchedData;

/**
 * Class _ForeignValuesSets was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ForeignValuesSets extends CayenneDataObject {

    public static final String ID_FOREIGN_VALUES_SET_PROPERTY = "idForeignValuesSet";
    public static final String FOREIGNVALUESES_PROPERTY = "foreignvalueses";
    public static final String FOREIGNVALUESSETS_COLLISIONSS_PROPERTY = "foreignvaluessetsCollisionss";
    public static final String TO_REFS_MATCHED_DATA_PROPERTY = "toRefsMatchedData";

    public static final String ID_FOREIGN_VALUES_SET_PK_COLUMN = "idForeignValuesSet";

    public void setIdForeignValuesSet(Short idForeignValuesSet) {
        writeProperty(ID_FOREIGN_VALUES_SET_PROPERTY, idForeignValuesSet);
    }
    public Short getIdForeignValuesSet() {
        return (Short)readProperty(ID_FOREIGN_VALUES_SET_PROPERTY);
    }

    public void addToForeignvalueses(ForeignValues obj) {
        addToManyTarget(FOREIGNVALUESES_PROPERTY, obj, true);
    }
    public void removeFromForeignvalueses(ForeignValues obj) {
        removeToManyTarget(FOREIGNVALUESES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ForeignValues> getForeignvalueses() {
        return (List<ForeignValues>)readProperty(FOREIGNVALUESES_PROPERTY);
    }


    public void addToForeignvaluessetsCollisionss(ForeignValuesSetsCollisions obj) {
        addToManyTarget(FOREIGNVALUESSETS_COLLISIONSS_PROPERTY, obj, true);
    }
    public void removeFromForeignvaluessetsCollisionss(ForeignValuesSetsCollisions obj) {
        removeToManyTarget(FOREIGNVALUESSETS_COLLISIONSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ForeignValuesSetsCollisions> getForeignvaluessetsCollisionss() {
        return (List<ForeignValuesSetsCollisions>)readProperty(FOREIGNVALUESSETS_COLLISIONSS_PROPERTY);
    }


    public void setToRefsMatchedData(RefsMatchedData toRefsMatchedData) {
        setToOneTarget(TO_REFS_MATCHED_DATA_PROPERTY, toRefsMatchedData, true);
    }

    public RefsMatchedData getToRefsMatchedData() {
        return (RefsMatchedData)readProperty(TO_REFS_MATCHED_DATA_PROPERTY);
    }


}
