package org.vamdc.basecolTest.dao.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.EnergyTablesLevels;
import org.vamdc.BasecolTest.dao.ForeignValuesSets;

/**
 * Class _ForeignValues was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ForeignValues extends CayenneDataObject {

    public static final String EINSTEIN_COEFFICIENT_PROPERTY = "einsteinCoefficient";
    public static final String FINAL_LEVEL_OF_PROPERTY = "finalLevelOf";
    public static final String FREQUENCY_PROPERTY = "frequency";
    public static final String G_UP_PROPERTY = "gUp";
    public static final String ID_FOREIGN_VALUES_SET_PROPERTY = "idForeignValuesSet";
    public static final String INITIAL_LEVEL_OF_PROPERTY = "initialLevelOf";
    public static final String UNCERTAINTY_PROPERTY = "uncertainty";
    public static final String TO_ENERGY_TABLES_LEVELS_PROPERTY = "toEnergyTablesLevels";
    public static final String TO_ENERGY_TABLES_LEVELS1_PROPERTY = "toEnergyTablesLevels1";
    public static final String TO_FOREIGN_VALUES_SETS_PROPERTY = "toForeignValuesSets";

    public static final String FINAL_LEVEL_OF_PK_COLUMN = "finalLevelOf";
    public static final String ID_FOREIGN_VALUES_SET_PK_COLUMN = "idForeignValuesSet";
    public static final String INITIAL_LEVEL_OF_PK_COLUMN = "initialLevelOf";

    public void setEinsteinCoefficient(Double einsteinCoefficient) {
        writeProperty(EINSTEIN_COEFFICIENT_PROPERTY, einsteinCoefficient);
    }
    public Double getEinsteinCoefficient() {
        return (Double)readProperty(EINSTEIN_COEFFICIENT_PROPERTY);
    }

    public void setFinalLevelOf(Long finalLevelOf) {
        writeProperty(FINAL_LEVEL_OF_PROPERTY, finalLevelOf);
    }
    public Long getFinalLevelOf() {
        return (Long)readProperty(FINAL_LEVEL_OF_PROPERTY);
    }

    public void setFrequency(BigDecimal frequency) {
        writeProperty(FREQUENCY_PROPERTY, frequency);
    }
    public BigDecimal getFrequency() {
        return (BigDecimal)readProperty(FREQUENCY_PROPERTY);
    }

    public void setGUp(Short gUp) {
        writeProperty(G_UP_PROPERTY, gUp);
    }
    public Short getGUp() {
        return (Short)readProperty(G_UP_PROPERTY);
    }

    public void setIdForeignValuesSet(Short idForeignValuesSet) {
        writeProperty(ID_FOREIGN_VALUES_SET_PROPERTY, idForeignValuesSet);
    }
    public Short getIdForeignValuesSet() {
        return (Short)readProperty(ID_FOREIGN_VALUES_SET_PROPERTY);
    }

    public void setInitialLevelOf(Long initialLevelOf) {
        writeProperty(INITIAL_LEVEL_OF_PROPERTY, initialLevelOf);
    }
    public Long getInitialLevelOf() {
        return (Long)readProperty(INITIAL_LEVEL_OF_PROPERTY);
    }

    public void setUncertainty(BigDecimal uncertainty) {
        writeProperty(UNCERTAINTY_PROPERTY, uncertainty);
    }
    public BigDecimal getUncertainty() {
        return (BigDecimal)readProperty(UNCERTAINTY_PROPERTY);
    }

    public void setToEnergyTablesLevels(EnergyTablesLevels toEnergyTablesLevels) {
        setToOneTarget(TO_ENERGY_TABLES_LEVELS_PROPERTY, toEnergyTablesLevels, true);
    }

    public EnergyTablesLevels getToEnergyTablesLevels() {
        return (EnergyTablesLevels)readProperty(TO_ENERGY_TABLES_LEVELS_PROPERTY);
    }


    public void setToEnergyTablesLevels1(EnergyTablesLevels toEnergyTablesLevels1) {
        setToOneTarget(TO_ENERGY_TABLES_LEVELS1_PROPERTY, toEnergyTablesLevels1, true);
    }

    public EnergyTablesLevels getToEnergyTablesLevels1() {
        return (EnergyTablesLevels)readProperty(TO_ENERGY_TABLES_LEVELS1_PROPERTY);
    }


    public void setToForeignValuesSets(ForeignValuesSets toForeignValuesSets) {
        setToOneTarget(TO_FOREIGN_VALUES_SETS_PROPERTY, toForeignValuesSets, true);
    }

    public ForeignValuesSets getToForeignValuesSets() {
        return (ForeignValuesSets)readProperty(TO_FOREIGN_VALUES_SETS_PROPERTY);
    }


}
