package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.EnergyTables;
import org.vamdc.BasecolTest.dao.MoleculeAtoms;
import org.vamdc.BasecolTest.dao.QuantumNumbers;

/**
 * Class _HyperfineQNums was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _HyperfineQNums extends CayenneDataObject {

    public static final String ID_MOL_NUCLEUS_PROPERTY = "idMolNucleus";
    public static final String ID_QNUMBER_PROPERTY = "idQNumber";
    public static final String ID_RECORD_PROPERTY = "idRecord";
    public static final String ID_REF_QNUMBER_PROPERTY = "idRefQNumber";
    public static final String TO_ENERGY_TABLES_PROPERTY = "toEnergyTables";
    public static final String TO_MOLECULE_ATOMS_PROPERTY = "toMoleculeAtoms";
    public static final String TO_QUANTUM_NUMBERS_PROPERTY = "toQuantumNumbers";
    public static final String TO_QUANTUM_NUMBERS1_PROPERTY = "toQuantumNumbers1";

    public static final String ID_RECORD_PK_COLUMN = "idRecord";

    public void setIdMolNucleus(Integer idMolNucleus) {
        writeProperty(ID_MOL_NUCLEUS_PROPERTY, idMolNucleus);
    }
    public Integer getIdMolNucleus() {
        return (Integer)readProperty(ID_MOL_NUCLEUS_PROPERTY);
    }

    public void setIdQNumber(Long idQNumber) {
        writeProperty(ID_QNUMBER_PROPERTY, idQNumber);
    }
    public Long getIdQNumber() {
        return (Long)readProperty(ID_QNUMBER_PROPERTY);
    }

    public void setIdRecord(Long idRecord) {
        writeProperty(ID_RECORD_PROPERTY, idRecord);
    }
    public Long getIdRecord() {
        return (Long)readProperty(ID_RECORD_PROPERTY);
    }

    public void setIdRefQNumber(Long idRefQNumber) {
        writeProperty(ID_REF_QNUMBER_PROPERTY, idRefQNumber);
    }
    public Long getIdRefQNumber() {
        return (Long)readProperty(ID_REF_QNUMBER_PROPERTY);
    }

    public void setToEnergyTables(EnergyTables toEnergyTables) {
        setToOneTarget(TO_ENERGY_TABLES_PROPERTY, toEnergyTables, true);
    }

    public EnergyTables getToEnergyTables() {
        return (EnergyTables)readProperty(TO_ENERGY_TABLES_PROPERTY);
    }


    public void setToMoleculeAtoms(MoleculeAtoms toMoleculeAtoms) {
        setToOneTarget(TO_MOLECULE_ATOMS_PROPERTY, toMoleculeAtoms, true);
    }

    public MoleculeAtoms getToMoleculeAtoms() {
        return (MoleculeAtoms)readProperty(TO_MOLECULE_ATOMS_PROPERTY);
    }


    public void setToQuantumNumbers(QuantumNumbers toQuantumNumbers) {
        setToOneTarget(TO_QUANTUM_NUMBERS_PROPERTY, toQuantumNumbers, true);
    }

    public QuantumNumbers getToQuantumNumbers() {
        return (QuantumNumbers)readProperty(TO_QUANTUM_NUMBERS_PROPERTY);
    }


    public void setToQuantumNumbers1(QuantumNumbers toQuantumNumbers1) {
        setToOneTarget(TO_QUANTUM_NUMBERS1_PROPERTY, toQuantumNumbers1, true);
    }

    public QuantumNumbers getToQuantumNumbers1() {
        return (QuantumNumbers)readProperty(TO_QUANTUM_NUMBERS1_PROPERTY);
    }


}
