package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Collisions;
import org.vamdc.BasecolTest.dao.EnergyTablesLevels;
import org.vamdc.BasecolTest.dao.FitValues;
import org.vamdc.BasecolTest.dao.RateCoefficients;

/**
 * Class _LevelGroups was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LevelGroups extends CayenneDataObject {

    public static final String ID_LEVEL_GROUP_PROPERTY = "idLevelGroup";
    public static final String FITVALUESES_PROPERTY = "fitvalueses";
    public static final String RATECOEFFICIENTSS_PROPERTY = "ratecoefficientss";
    public static final String TO_COLLISIONS_PROPERTY = "toCollisions";
    public static final String TO_ETLFINAL_COLLIDER_PROPERTY = "toETLFinalCollider";
    public static final String TO_ETLFINAL_TARGET_PROPERTY = "toETLFinalTarget";
    public static final String TO_ETLINIT_COLLIDER_PROPERTY = "toETLInitCollider";
    public static final String TO_ETLINIT_TARGET_PROPERTY = "toETLInitTarget";

    public static final String ID_LEVEL_GROUP_PK_COLUMN = "idLevelGroup";

    public void setIdLevelGroup(Long idLevelGroup) {
        writeProperty(ID_LEVEL_GROUP_PROPERTY, idLevelGroup);
    }
    public Long getIdLevelGroup() {
        return (Long)readProperty(ID_LEVEL_GROUP_PROPERTY);
    }

    public void addToFitvalueses(FitValues obj) {
        addToManyTarget(FITVALUESES_PROPERTY, obj, true);
    }
    public void removeFromFitvalueses(FitValues obj) {
        removeToManyTarget(FITVALUESES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FitValues> getFitvalueses() {
        return (List<FitValues>)readProperty(FITVALUESES_PROPERTY);
    }


    public void addToRatecoefficientss(RateCoefficients obj) {
        addToManyTarget(RATECOEFFICIENTSS_PROPERTY, obj, true);
    }
    public void removeFromRatecoefficientss(RateCoefficients obj) {
        removeToManyTarget(RATECOEFFICIENTSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RateCoefficients> getRatecoefficientss() {
        return (List<RateCoefficients>)readProperty(RATECOEFFICIENTSS_PROPERTY);
    }


    public void setToCollisions(Collisions toCollisions) {
        setToOneTarget(TO_COLLISIONS_PROPERTY, toCollisions, true);
    }

    public Collisions getToCollisions() {
        return (Collisions)readProperty(TO_COLLISIONS_PROPERTY);
    }


    public void setToETLFinalCollider(EnergyTablesLevels toETLFinalCollider) {
        setToOneTarget(TO_ETLFINAL_COLLIDER_PROPERTY, toETLFinalCollider, true);
    }

    public EnergyTablesLevels getToETLFinalCollider() {
        return (EnergyTablesLevels)readProperty(TO_ETLFINAL_COLLIDER_PROPERTY);
    }


    public void setToETLFinalTarget(EnergyTablesLevels toETLFinalTarget) {
        setToOneTarget(TO_ETLFINAL_TARGET_PROPERTY, toETLFinalTarget, true);
    }

    public EnergyTablesLevels getToETLFinalTarget() {
        return (EnergyTablesLevels)readProperty(TO_ETLFINAL_TARGET_PROPERTY);
    }


    public void setToETLInitCollider(EnergyTablesLevels toETLInitCollider) {
        setToOneTarget(TO_ETLINIT_COLLIDER_PROPERTY, toETLInitCollider, true);
    }

    public EnergyTablesLevels getToETLInitCollider() {
        return (EnergyTablesLevels)readProperty(TO_ETLINIT_COLLIDER_PROPERTY);
    }


    public void setToETLInitTarget(EnergyTablesLevels toETLInitTarget) {
        setToOneTarget(TO_ETLINIT_TARGET_PROPERTY, toETLInitTarget, true);
    }

    public EnergyTablesLevels getToETLInitTarget() {
        return (EnergyTablesLevels)readProperty(TO_ETLINIT_TARGET_PROPERTY);
    }


}
