package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Collisions;
import org.vamdc.BasecolTest.dao.MatchedEnergyTables;

/**
 * Class _MatchedEnergyTablesCollisions was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MatchedEnergyTablesCollisions extends CayenneDataObject {

    public static final String ID_COLLISION_PROPERTY = "idCollision";
    public static final String ID_MATCHED_ENERGY_TABLE_PROPERTY = "idMatchedEnergyTable";
    public static final String TO_COLLISIONS_PROPERTY = "toCollisions";
    public static final String TO_MATCHED_ENERGY_TABLES_PROPERTY = "toMatchedEnergyTables";

    public static final String ID_COLLISION_PK_COLUMN = "idCollision";
    public static final String ID_MATCHED_ENERGY_TABLE_PK_COLUMN = "idMatchedEnergyTable";

    public void setIdCollision(Long idCollision) {
        writeProperty(ID_COLLISION_PROPERTY, idCollision);
    }
    public Long getIdCollision() {
        return (Long)readProperty(ID_COLLISION_PROPERTY);
    }

    public void setIdMatchedEnergyTable(Short idMatchedEnergyTable) {
        writeProperty(ID_MATCHED_ENERGY_TABLE_PROPERTY, idMatchedEnergyTable);
    }
    public Short getIdMatchedEnergyTable() {
        return (Short)readProperty(ID_MATCHED_ENERGY_TABLE_PROPERTY);
    }

    public void setToCollisions(Collisions toCollisions) {
        setToOneTarget(TO_COLLISIONS_PROPERTY, toCollisions, true);
    }

    public Collisions getToCollisions() {
        return (Collisions)readProperty(TO_COLLISIONS_PROPERTY);
    }


    public void setToMatchedEnergyTables(MatchedEnergyTables toMatchedEnergyTables) {
        setToOneTarget(TO_MATCHED_ENERGY_TABLES_PROPERTY, toMatchedEnergyTables, true);
    }

    public MatchedEnergyTables getToMatchedEnergyTables() {
        return (MatchedEnergyTables)readProperty(TO_MATCHED_ENERGY_TABLES_PROPERTY);
    }


}
