package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.EnergyTables;
import org.vamdc.BasecolTest.dao.MatchedEnergyTablesCollisions;
import org.vamdc.BasecolTest.dao.MatchedEnergyTablesLevels;
import org.vamdc.BasecolTest.dao.RefsMatchedData;

/**
 * Class _MatchedEnergyTables was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MatchedEnergyTables extends CayenneDataObject {

    public static final String ID_MATCHED_ENERGY_TABLE_PROPERTY = "idMatchedEnergyTable";
    public static final String MATCHEDENERGYTABLES_COLLISIONSS_PROPERTY = "matchedenergytablesCollisionss";
    public static final String MATCHEDENERGYTABLES_LEVELSS_PROPERTY = "matchedenergytablesLevelss";
    public static final String TO_ENERGY_TABLES_PROPERTY = "toEnergyTables";
    public static final String TO_REFS_MATCHED_DATA_PROPERTY = "toRefsMatchedData";

    public static final String ID_MATCHED_ENERGY_TABLE_PK_COLUMN = "idMatchedEnergyTable";

    public void setIdMatchedEnergyTable(Short idMatchedEnergyTable) {
        writeProperty(ID_MATCHED_ENERGY_TABLE_PROPERTY, idMatchedEnergyTable);
    }
    public Short getIdMatchedEnergyTable() {
        return (Short)readProperty(ID_MATCHED_ENERGY_TABLE_PROPERTY);
    }

    public void addToMatchedenergytablesCollisionss(MatchedEnergyTablesCollisions obj) {
        addToManyTarget(MATCHEDENERGYTABLES_COLLISIONSS_PROPERTY, obj, true);
    }
    public void removeFromMatchedenergytablesCollisionss(MatchedEnergyTablesCollisions obj) {
        removeToManyTarget(MATCHEDENERGYTABLES_COLLISIONSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MatchedEnergyTablesCollisions> getMatchedenergytablesCollisionss() {
        return (List<MatchedEnergyTablesCollisions>)readProperty(MATCHEDENERGYTABLES_COLLISIONSS_PROPERTY);
    }


    public void addToMatchedenergytablesLevelss(MatchedEnergyTablesLevels obj) {
        addToManyTarget(MATCHEDENERGYTABLES_LEVELSS_PROPERTY, obj, true);
    }
    public void removeFromMatchedenergytablesLevelss(MatchedEnergyTablesLevels obj) {
        removeToManyTarget(MATCHEDENERGYTABLES_LEVELSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MatchedEnergyTablesLevels> getMatchedenergytablesLevelss() {
        return (List<MatchedEnergyTablesLevels>)readProperty(MATCHEDENERGYTABLES_LEVELSS_PROPERTY);
    }


    public void setToEnergyTables(EnergyTables toEnergyTables) {
        setToOneTarget(TO_ENERGY_TABLES_PROPERTY, toEnergyTables, true);
    }

    public EnergyTables getToEnergyTables() {
        return (EnergyTables)readProperty(TO_ENERGY_TABLES_PROPERTY);
    }


    public void setToRefsMatchedData(RefsMatchedData toRefsMatchedData) {
        setToOneTarget(TO_REFS_MATCHED_DATA_PROPERTY, toRefsMatchedData, true);
    }

    public RefsMatchedData getToRefsMatchedData() {
        return (RefsMatchedData)readProperty(TO_REFS_MATCHED_DATA_PROPERTY);
    }


}
