package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.EnergyTablesLevels;
import org.vamdc.BasecolTest.dao.MatchedEnergyTables;

/**
 * Class _MatchedEnergyTablesLevels was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MatchedEnergyTablesLevels extends CayenneDataObject {

    public static final String DEGENERACY_PROPERTY = "degeneracy";
    public static final String ENERGY_PROPERTY = "energy";
    public static final String ID_MATCHED_LEVEL_PROPERTY = "idMatchedLevel";
    public static final String TO_ENERGY_TABLES_LEVELS_PROPERTY = "toEnergyTablesLevels";
    public static final String TO_MATCHED_ENERGY_TABLES_PROPERTY = "toMatchedEnergyTables";

    public static final String ID_MATCHED_LEVEL_PK_COLUMN = "idMatchedLevel";

    public void setDegeneracy(Integer degeneracy) {
        writeProperty(DEGENERACY_PROPERTY, degeneracy);
    }
    public Integer getDegeneracy() {
        return (Integer)readProperty(DEGENERACY_PROPERTY);
    }

    public void setEnergy(Double energy) {
        writeProperty(ENERGY_PROPERTY, energy);
    }
    public Double getEnergy() {
        return (Double)readProperty(ENERGY_PROPERTY);
    }

    public void setIdMatchedLevel(Integer idMatchedLevel) {
        writeProperty(ID_MATCHED_LEVEL_PROPERTY, idMatchedLevel);
    }
    public Integer getIdMatchedLevel() {
        return (Integer)readProperty(ID_MATCHED_LEVEL_PROPERTY);
    }

    public void setToEnergyTablesLevels(EnergyTablesLevels toEnergyTablesLevels) {
        setToOneTarget(TO_ENERGY_TABLES_LEVELS_PROPERTY, toEnergyTablesLevels, true);
    }

    public EnergyTablesLevels getToEnergyTablesLevels() {
        return (EnergyTablesLevels)readProperty(TO_ENERGY_TABLES_LEVELS_PROPERTY);
    }


    public void setToMatchedEnergyTables(MatchedEnergyTables toMatchedEnergyTables) {
        setToOneTarget(TO_MATCHED_ENERGY_TABLES_PROPERTY, toMatchedEnergyTables, true);
    }

    public MatchedEnergyTables getToMatchedEnergyTables() {
        return (MatchedEnergyTables)readProperty(TO_MATCHED_ENERGY_TABLES_PROPERTY);
    }


}
