package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.CollaborationGroups;

/**
 * Class _Members was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Members extends CayenneDataObject {

    public static final String EMAIL_PROPERTY = "email";
    public static final String FIRSTNAME_PROPERTY = "firstname";
    public static final String FUNCTION_PROPERTY = "function";
    public static final String ID_MEMBER_PROPERTY = "idMember";
    public static final String SITE_PROPERTY = "site";
    public static final String SURNAME_PROPERTY = "surname";
    public static final String TELEPHONE_PROPERTY = "telephone";
    public static final String TO_COLLABORATION_GROUPS_PROPERTY = "toCollaborationGroups";

    public static final String ID_MEMBER_PK_COLUMN = "idMember";

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setFirstname(String firstname) {
        writeProperty(FIRSTNAME_PROPERTY, firstname);
    }
    public String getFirstname() {
        return (String)readProperty(FIRSTNAME_PROPERTY);
    }

    public void setFunction(String function) {
        writeProperty(FUNCTION_PROPERTY, function);
    }
    public String getFunction() {
        return (String)readProperty(FUNCTION_PROPERTY);
    }

    public void setIdMember(Long idMember) {
        writeProperty(ID_MEMBER_PROPERTY, idMember);
    }
    public Long getIdMember() {
        return (Long)readProperty(ID_MEMBER_PROPERTY);
    }

    public void setSite(String site) {
        writeProperty(SITE_PROPERTY, site);
    }
    public String getSite() {
        return (String)readProperty(SITE_PROPERTY);
    }

    public void setSurname(String surname) {
        writeProperty(SURNAME_PROPERTY, surname);
    }
    public String getSurname() {
        return (String)readProperty(SURNAME_PROPERTY);
    }

    public void setTelephone(String telephone) {
        writeProperty(TELEPHONE_PROPERTY, telephone);
    }
    public String getTelephone() {
        return (String)readProperty(TELEPHONE_PROPERTY);
    }

    public void setToCollaborationGroups(CollaborationGroups toCollaborationGroups) {
        setToOneTarget(TO_COLLABORATION_GROUPS_PROPERTY, toCollaborationGroups, true);
    }

    public CollaborationGroups getToCollaborationGroups() {
        return (CollaborationGroups)readProperty(TO_COLLABORATION_GROUPS_PROPERTY);
    }


}
