package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Elements;
import org.vamdc.BasecolTest.dao.MoleculeAtoms;

/**
 * Class _MoleculeBonds was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MoleculeBonds extends CayenneDataObject {

    public static final String BOND_ID_PROPERTY = "bondId";
    public static final String BOND_ORDER_PROPERTY = "bondOrder";
    public static final String ATOM1_PROPERTY = "atom1";
    public static final String ATOM2_PROPERTY = "atom2";
    public static final String TO_ELEMENTS_PROPERTY = "toElements";

    public static final String BOND_ID_PK_COLUMN = "bond_id";

    public void setBondId(Integer bondId) {
        writeProperty(BOND_ID_PROPERTY, bondId);
    }
    public Integer getBondId() {
        return (Integer)readProperty(BOND_ID_PROPERTY);
    }

    public void setBondOrder(String bondOrder) {
        writeProperty(BOND_ORDER_PROPERTY, bondOrder);
    }
    public String getBondOrder() {
        return (String)readProperty(BOND_ORDER_PROPERTY);
    }

    public void setAtom1(MoleculeAtoms atom1) {
        setToOneTarget(ATOM1_PROPERTY, atom1, true);
    }

    public MoleculeAtoms getAtom1() {
        return (MoleculeAtoms)readProperty(ATOM1_PROPERTY);
    }


    public void setAtom2(MoleculeAtoms atom2) {
        setToOneTarget(ATOM2_PROPERTY, atom2, true);
    }

    public MoleculeAtoms getAtom2() {
        return (MoleculeAtoms)readProperty(ATOM2_PROPERTY);
    }


    public void setToElements(Elements toElements) {
        setToOneTarget(TO_ELEMENTS_PROPERTY, toElements, true);
    }

    public Elements getToElements() {
        return (Elements)readProperty(TO_ELEMENTS_PROPERTY);
    }


}
