package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Elements;
import org.vamdc.BasecolTest.dao.HyperfineQNums;
import org.vamdc.BasecolTest.dao.MoleculeBonds;
import org.vamdc.BasecolTest.dao.Nuclei;

/**
 * Class _MoleculeAtoms was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _MoleculeAtoms extends CayenneDataObject {

    public static final String ATOM_CHARGE_PROPERTY = "atomCharge";
    public static final String ATOM_COUNT_PROPERTY = "atomCount";
    public static final String ATOM_ID_PROPERTY = "atomId";
    public static final String HYDROGEN_COUNT_PROPERTY = "hydrogenCount";
    public static final String HYPERFINE_QNUMSS_PROPERTY = "hyperfineQnumss";
    public static final String MOLECULEBONDSS_PROPERTY = "moleculebondss";
    public static final String MOLECULEBONDSS1_PROPERTY = "moleculebondss1";
    public static final String NUCLEUS_PROPERTY = "nucleus";
    public static final String TO_ELEMENTS_PROPERTY = "toElements";

    public static final String ATOM_ID_PK_COLUMN = "atom_id";

    public void setAtomCharge(Short atomCharge) {
        writeProperty(ATOM_CHARGE_PROPERTY, atomCharge);
    }
    public Short getAtomCharge() {
        return (Short)readProperty(ATOM_CHARGE_PROPERTY);
    }

    public void setAtomCount(Short atomCount) {
        writeProperty(ATOM_COUNT_PROPERTY, atomCount);
    }
    public Short getAtomCount() {
        return (Short)readProperty(ATOM_COUNT_PROPERTY);
    }

    public void setAtomId(Integer atomId) {
        writeProperty(ATOM_ID_PROPERTY, atomId);
    }
    public Integer getAtomId() {
        return (Integer)readProperty(ATOM_ID_PROPERTY);
    }

    public void setHydrogenCount(Short hydrogenCount) {
        writeProperty(HYDROGEN_COUNT_PROPERTY, hydrogenCount);
    }
    public Short getHydrogenCount() {
        return (Short)readProperty(HYDROGEN_COUNT_PROPERTY);
    }

    public void addToHyperfineQnumss(HyperfineQNums obj) {
        addToManyTarget(HYPERFINE_QNUMSS_PROPERTY, obj, true);
    }
    public void removeFromHyperfineQnumss(HyperfineQNums obj) {
        removeToManyTarget(HYPERFINE_QNUMSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<HyperfineQNums> getHyperfineQnumss() {
        return (List<HyperfineQNums>)readProperty(HYPERFINE_QNUMSS_PROPERTY);
    }


    public void addToMoleculebondss(MoleculeBonds obj) {
        addToManyTarget(MOLECULEBONDSS_PROPERTY, obj, true);
    }
    public void removeFromMoleculebondss(MoleculeBonds obj) {
        removeToManyTarget(MOLECULEBONDSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MoleculeBonds> getMoleculebondss() {
        return (List<MoleculeBonds>)readProperty(MOLECULEBONDSS_PROPERTY);
    }


    public void addToMoleculebondss1(MoleculeBonds obj) {
        addToManyTarget(MOLECULEBONDSS1_PROPERTY, obj, true);
    }
    public void removeFromMoleculebondss1(MoleculeBonds obj) {
        removeToManyTarget(MOLECULEBONDSS1_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MoleculeBonds> getMoleculebondss1() {
        return (List<MoleculeBonds>)readProperty(MOLECULEBONDSS1_PROPERTY);
    }


    public void setNucleus(Nuclei nucleus) {
        setToOneTarget(NUCLEUS_PROPERTY, nucleus, true);
    }

    public Nuclei getNucleus() {
        return (Nuclei)readProperty(NUCLEUS_PROPERTY);
    }


    public void setToElements(Elements toElements) {
        setToOneTarget(TO_ELEMENTS_PROPERTY, toElements, true);
    }

    public Elements getToElements() {
        return (Elements)readProperty(TO_ELEMENTS_PROPERTY);
    }


}
