package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.PartitionFunctions;

/**
 * Class _PartitionFunctionsValues was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PartitionFunctionsValues extends CayenneDataObject {

    public static final String ID_PARTITION_PROPERTY = "idPartition";
    public static final String Q_PROPERTY = "q";
    public static final String T_PROPERTY = "t";
    public static final String TO_PARTITION_FUNCTIONS_PROPERTY = "toPartitionFunctions";

    public static final String T_PK_COLUMN = "T";
    public static final String ID_PARTITION_PK_COLUMN = "idPartition";

    public void setIdPartition(Long idPartition) {
        writeProperty(ID_PARTITION_PROPERTY, idPartition);
    }
    public Long getIdPartition() {
        return (Long)readProperty(ID_PARTITION_PROPERTY);
    }

    public void setQ(Double q) {
        writeProperty(Q_PROPERTY, q);
    }
    public Double getQ() {
        return (Double)readProperty(Q_PROPERTY);
    }

    public void setT(Double t) {
        writeProperty(T_PROPERTY, t);
    }
    public Double getT() {
        return (Double)readProperty(T_PROPERTY);
    }

    public void setToPartitionFunctions(PartitionFunctions toPartitionFunctions) {
        setToOneTarget(TO_PARTITION_FUNCTIONS_PROPERTY, toPartitionFunctions, true);
    }

    public PartitionFunctions getToPartitionFunctions() {
        return (PartitionFunctions)readProperty(TO_PARTITION_FUNCTIONS_PROPERTY);
    }


}
