package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.CollisionsProcessus;
import org.vamdc.BasecolTest.dao.EnergyTablesProcessus;

/**
 * Class _Processus was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Processus extends CayenneDataObject {

    public static final String DESIGNATION_PROPERTY = "designation";
    public static final String ID_PROCESSUS_PROPERTY = "idProcessus";
    public static final String COLLISIONS_PROCESSUSES_PROPERTY = "collisionsProcessuses";
    public static final String ENERGYTABLES_PROCESSUSES_PROPERTY = "energytablesProcessuses";

    public static final String ID_PROCESSUS_PK_COLUMN = "idProcessus";

    public void setDesignation(String designation) {
        writeProperty(DESIGNATION_PROPERTY, designation);
    }
    public String getDesignation() {
        return (String)readProperty(DESIGNATION_PROPERTY);
    }

    public void setIdProcessus(Short idProcessus) {
        writeProperty(ID_PROCESSUS_PROPERTY, idProcessus);
    }
    public Short getIdProcessus() {
        return (Short)readProperty(ID_PROCESSUS_PROPERTY);
    }

    public void addToCollisionsProcessuses(CollisionsProcessus obj) {
        addToManyTarget(COLLISIONS_PROCESSUSES_PROPERTY, obj, true);
    }
    public void removeFromCollisionsProcessuses(CollisionsProcessus obj) {
        removeToManyTarget(COLLISIONS_PROCESSUSES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CollisionsProcessus> getCollisionsProcessuses() {
        return (List<CollisionsProcessus>)readProperty(COLLISIONS_PROCESSUSES_PROPERTY);
    }


    public void addToEnergytablesProcessuses(EnergyTablesProcessus obj) {
        addToManyTarget(ENERGYTABLES_PROCESSUSES_PROPERTY, obj, true);
    }
    public void removeFromEnergytablesProcessuses(EnergyTablesProcessus obj) {
        removeToManyTarget(ENERGYTABLES_PROCESSUSES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EnergyTablesProcessus> getEnergytablesProcessuses() {
        return (List<EnergyTablesProcessus>)readProperty(ENERGYTABLES_PROCESSUSES_PROPERTY);
    }


}
