package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Publications was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Publications extends CayenneDataObject {

    public static final String AUTHORS_PROPERTY = "authors";
    public static final String ID_PUBLICATION_PROPERTY = "idPublication";
    public static final String JOURNAL_PROPERTY = "journal";
    public static final String LINK_PROPERTY = "link";
    public static final String TITLE_PROPERTY = "title";
    public static final String TYPE_PROPERTY = "type";
    public static final String YEAR_PROPERTY = "year";

    public static final String ID_PUBLICATION_PK_COLUMN = "idPublication";

    public void setAuthors(String authors) {
        writeProperty(AUTHORS_PROPERTY, authors);
    }
    public String getAuthors() {
        return (String)readProperty(AUTHORS_PROPERTY);
    }

    public void setIdPublication(Long idPublication) {
        writeProperty(ID_PUBLICATION_PROPERTY, idPublication);
    }
    public Long getIdPublication() {
        return (Long)readProperty(ID_PUBLICATION_PROPERTY);
    }

    public void setJournal(String journal) {
        writeProperty(JOURNAL_PROPERTY, journal);
    }
    public String getJournal() {
        return (String)readProperty(JOURNAL_PROPERTY);
    }

    public void setLink(String link) {
        writeProperty(LINK_PROPERTY, link);
    }
    public String getLink() {
        return (String)readProperty(LINK_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void setType(String type) {
        writeProperty(TYPE_PROPERTY, type);
    }
    public String getType() {
        return (String)readProperty(TYPE_PROPERTY);
    }

    public void setYear(Integer year) {
        writeProperty(YEAR_PROPERTY, year);
    }
    public Integer getYear() {
        return (Integer)readProperty(YEAR_PROPERTY);
    }

}
