package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.EnergyTablesLevelsQuantumNumbers;
import org.vamdc.BasecolTest.dao.EnergyTablesQuantumNumbers;
import org.vamdc.BasecolTest.dao.HyperfineQNums;

/**
 * Class _QuantumNumbers was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _QuantumNumbers extends CayenneDataObject {

    public static final String COMMENT_PROPERTY = "comment";
    public static final String DESIGNATION_PROPERTY = "designation";
    public static final String ID_QUANTUM_NUMBER_PROPERTY = "idQuantumNumber";
    public static final String ENERGYTABLES_LEVELS_QUANTUMNUMBERSS_PROPERTY = "energytablesLevelsQuantumnumberss";
    public static final String ENERGYTABLES_QUANTUMNUMBERSS_PROPERTY = "energytablesQuantumnumberss";
    public static final String HYPERFINE_QNUMSS_PROPERTY = "hyperfineQnumss";
    public static final String HYPERFINE_QNUMSS1_PROPERTY = "hyperfineQnumss1";

    public static final String ID_QUANTUM_NUMBER_PK_COLUMN = "idQuantumNumber";

    public void setComment(String comment) {
        writeProperty(COMMENT_PROPERTY, comment);
    }
    public String getComment() {
        return (String)readProperty(COMMENT_PROPERTY);
    }

    public void setDesignation(String designation) {
        writeProperty(DESIGNATION_PROPERTY, designation);
    }
    public String getDesignation() {
        return (String)readProperty(DESIGNATION_PROPERTY);
    }

    public void setIdQuantumNumber(Long idQuantumNumber) {
        writeProperty(ID_QUANTUM_NUMBER_PROPERTY, idQuantumNumber);
    }
    public Long getIdQuantumNumber() {
        return (Long)readProperty(ID_QUANTUM_NUMBER_PROPERTY);
    }

    public void addToEnergytablesLevelsQuantumnumberss(EnergyTablesLevelsQuantumNumbers obj) {
        addToManyTarget(ENERGYTABLES_LEVELS_QUANTUMNUMBERSS_PROPERTY, obj, true);
    }
    public void removeFromEnergytablesLevelsQuantumnumberss(EnergyTablesLevelsQuantumNumbers obj) {
        removeToManyTarget(ENERGYTABLES_LEVELS_QUANTUMNUMBERSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EnergyTablesLevelsQuantumNumbers> getEnergytablesLevelsQuantumnumberss() {
        return (List<EnergyTablesLevelsQuantumNumbers>)readProperty(ENERGYTABLES_LEVELS_QUANTUMNUMBERSS_PROPERTY);
    }


    public void addToEnergytablesQuantumnumberss(EnergyTablesQuantumNumbers obj) {
        addToManyTarget(ENERGYTABLES_QUANTUMNUMBERSS_PROPERTY, obj, true);
    }
    public void removeFromEnergytablesQuantumnumberss(EnergyTablesQuantumNumbers obj) {
        removeToManyTarget(ENERGYTABLES_QUANTUMNUMBERSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<EnergyTablesQuantumNumbers> getEnergytablesQuantumnumberss() {
        return (List<EnergyTablesQuantumNumbers>)readProperty(ENERGYTABLES_QUANTUMNUMBERSS_PROPERTY);
    }


    public void addToHyperfineQnumss(HyperfineQNums obj) {
        addToManyTarget(HYPERFINE_QNUMSS_PROPERTY, obj, true);
    }
    public void removeFromHyperfineQnumss(HyperfineQNums obj) {
        removeToManyTarget(HYPERFINE_QNUMSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<HyperfineQNums> getHyperfineQnumss() {
        return (List<HyperfineQNums>)readProperty(HYPERFINE_QNUMSS_PROPERTY);
    }


    public void addToHyperfineQnumss1(HyperfineQNums obj) {
        addToManyTarget(HYPERFINE_QNUMSS1_PROPERTY, obj, true);
    }
    public void removeFromHyperfineQnumss1(HyperfineQNums obj) {
        removeToManyTarget(HYPERFINE_QNUMSS1_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<HyperfineQNums> getHyperfineQnumss1() {
        return (List<HyperfineQNums>)readProperty(HYPERFINE_QNUMSS1_PROPERTY);
    }


}
