package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Collisions;
import org.vamdc.BasecolTest.dao.LevelGroups;

/**
 * Class _RateCoefficients was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RateCoefficients extends CayenneDataObject {

    public static final String DATA_PROPERTY = "data";
    public static final String ID_RATE_PROPERTY = "idRate";
    public static final String IS_EFFECTIVE_RATE_PROPERTY = "isEffectiveRate";
    public static final String TEMPERATURE_PROPERTY = "temperature";
    public static final String TO_COLLISIONS_PROPERTY = "toCollisions";
    public static final String TO_LEVEL_GROUPS_PROPERTY = "toLevelGroups";

    public static final String ID_RATE_PK_COLUMN = "idRate";

    public void setData(Double data) {
        writeProperty(DATA_PROPERTY, data);
    }
    public Double getData() {
        return (Double)readProperty(DATA_PROPERTY);
    }

    public void setIdRate(Long idRate) {
        writeProperty(ID_RATE_PROPERTY, idRate);
    }
    public Long getIdRate() {
        return (Long)readProperty(ID_RATE_PROPERTY);
    }

    public void setIsEffectiveRate(Boolean isEffectiveRate) {
        writeProperty(IS_EFFECTIVE_RATE_PROPERTY, isEffectiveRate);
    }
    public Boolean getIsEffectiveRate() {
        return (Boolean)readProperty(IS_EFFECTIVE_RATE_PROPERTY);
    }

    public void setTemperature(Double temperature) {
        writeProperty(TEMPERATURE_PROPERTY, temperature);
    }
    public Double getTemperature() {
        return (Double)readProperty(TEMPERATURE_PROPERTY);
    }

    public void setToCollisions(Collisions toCollisions) {
        setToOneTarget(TO_COLLISIONS_PROPERTY, toCollisions, true);
    }

    public Collisions getToCollisions() {
        return (Collisions)readProperty(TO_COLLISIONS_PROPERTY);
    }


    public void setToLevelGroups(LevelGroups toLevelGroups) {
        setToOneTarget(TO_LEVEL_GROUPS_PROPERTY, toLevelGroups, true);
    }

    public LevelGroups getToLevelGroups() {
        return (LevelGroups)readProperty(TO_LEVEL_GROUPS_PROPERTY);
    }


}
