package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.RefsArticles;
import org.vamdc.BasecolTest.dao.RefsKeywords;

/**
 * Class _RefsArticlesKeywords was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RefsArticlesKeywords extends CayenneDataObject {

    public static final String TO_REFS_ARTICLES_PROPERTY = "toRefsArticles";
    public static final String TO_REFS_KEYWORDS_PROPERTY = "toRefsKeywords";

    public static final String ID_ARTICLE_PK_COLUMN = "idArticle";
    public static final String ID_KEYWORD_PK_COLUMN = "idKeyword";

    public void setToRefsArticles(RefsArticles toRefsArticles) {
        setToOneTarget(TO_REFS_ARTICLES_PROPERTY, toRefsArticles, true);
    }

    public RefsArticles getToRefsArticles() {
        return (RefsArticles)readProperty(TO_REFS_ARTICLES_PROPERTY);
    }


    public void setToRefsKeywords(RefsKeywords toRefsKeywords) {
        setToOneTarget(TO_REFS_KEYWORDS_PROPERTY, toRefsKeywords, true);
    }

    public RefsKeywords getToRefsKeywords() {
        return (RefsKeywords)readProperty(TO_REFS_KEYWORDS_PROPERTY);
    }


}
