package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.RefsArticles;

/**
 * Class _RefsAdsnotes was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RefsAdsnotes extends CayenneDataObject {

    public static final String ID_ADSNOTE_PROPERTY = "idAdsnote";
    public static final String VALUE_PROPERTY = "value";
    public static final String REFS_ARTICLESES_PROPERTY = "refsArticleses";

    public static final String ID_ADSNOTE_PK_COLUMN = "idAdsnote";

    public void setIdAdsnote(Long idAdsnote) {
        writeProperty(ID_ADSNOTE_PROPERTY, idAdsnote);
    }
    public Long getIdAdsnote() {
        return (Long)readProperty(ID_ADSNOTE_PROPERTY);
    }

    public void setValue(String value) {
        writeProperty(VALUE_PROPERTY, value);
    }
    public String getValue() {
        return (String)readProperty(VALUE_PROPERTY);
    }

    public void addToRefsArticleses(RefsArticles obj) {
        addToManyTarget(REFS_ARTICLESES_PROPERTY, obj, true);
    }
    public void removeFromRefsArticleses(RefsArticles obj) {
        removeToManyTarget(REFS_ARTICLESES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RefsArticles> getRefsArticleses() {
        return (List<RefsArticles>)readProperty(REFS_ARTICLESES_PROPERTY);
    }


}
