package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.RefsArticlesAuthors;

/**
 * Class _RefsAuthors was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RefsAuthors extends CayenneDataObject {

    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String ID_AUTHOR_PROPERTY = "idAuthor";
    public static final String SURNAME_PROPERTY = "surname";
    public static final String REFS_ARTICLES_AUTHORSS_PROPERTY = "refsArticlesAuthorss";

    public static final String ID_AUTHOR_PK_COLUMN = "idAuthor";

    public void setFirstName(String firstName) {
        writeProperty(FIRST_NAME_PROPERTY, firstName);
    }
    public String getFirstName() {
        return (String)readProperty(FIRST_NAME_PROPERTY);
    }

    public void setIdAuthor(Long idAuthor) {
        writeProperty(ID_AUTHOR_PROPERTY, idAuthor);
    }
    public Long getIdAuthor() {
        return (Long)readProperty(ID_AUTHOR_PROPERTY);
    }

    public void setSurname(String surname) {
        writeProperty(SURNAME_PROPERTY, surname);
    }
    public String getSurname() {
        return (String)readProperty(SURNAME_PROPERTY);
    }

    public void addToRefsArticlesAuthorss(RefsArticlesAuthors obj) {
        addToManyTarget(REFS_ARTICLES_AUTHORSS_PROPERTY, obj, true);
    }
    public void removeFromRefsArticlesAuthorss(RefsArticlesAuthors obj) {
        removeToManyTarget(REFS_ARTICLES_AUTHORSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RefsArticlesAuthors> getRefsArticlesAuthorss() {
        return (List<RefsArticlesAuthors>)readProperty(REFS_ARTICLES_AUTHORSS_PROPERTY);
    }


}
