package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.RefsArticles;

/**
 * Class _RefsJournals was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RefsJournals extends CayenneDataObject {

    public static final String CATEGORY_PROPERTY = "category";
    public static final String ID_JOURNAL_PROPERTY = "idJournal";
    public static final String NAME_PROPERTY = "name";
    public static final String SMALL_NAME_PROPERTY = "smallName";
    public static final String REFS_ARTICLESES_PROPERTY = "refsArticleses";

    public static final String ID_JOURNAL_PK_COLUMN = "idJournal";

    public void setCategory(String category) {
        writeProperty(CATEGORY_PROPERTY, category);
    }
    public String getCategory() {
        return (String)readProperty(CATEGORY_PROPERTY);
    }

    public void setIdJournal(Long idJournal) {
        writeProperty(ID_JOURNAL_PROPERTY, idJournal);
    }
    public Long getIdJournal() {
        return (Long)readProperty(ID_JOURNAL_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setSmallName(String smallName) {
        writeProperty(SMALL_NAME_PROPERTY, smallName);
    }
    public String getSmallName() {
        return (String)readProperty(SMALL_NAME_PROPERTY);
    }

    public void addToRefsArticleses(RefsArticles obj) {
        addToManyTarget(REFS_ARTICLESES_PROPERTY, obj, true);
    }
    public void removeFromRefsArticleses(RefsArticles obj) {
        removeToManyTarget(REFS_ARTICLESES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RefsArticles> getRefsArticleses() {
        return (List<RefsArticles>)readProperty(REFS_ARTICLESES_PROPERTY);
    }


}
