package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.RefsAdsnotes;
import org.vamdc.BasecolTest.dao.RefsArticlesAuthors;
import org.vamdc.BasecolTest.dao.RefsArticlesKeywords;
import org.vamdc.BasecolTest.dao.RefsAuthors;
import org.vamdc.BasecolTest.dao.RefsGroups;
import org.vamdc.BasecolTest.dao.RefsJournals;

/**
 * Class _RefsArticles was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RefsArticles extends CayenneDataObject {

    public static final String ID_ARTICLE_PROPERTY = "idArticle";
    public static final String ISSUE_PROPERTY = "issue";
    public static final String LINK_TO_DATA_PROPERTY = "linkToData";
    public static final String MONTH_PROPERTY = "month";
    public static final String PAGE_PROPERTY = "page";
    public static final String STATUS_PROPERTY = "status";
    public static final String TITLE_PROPERTY = "title";
    public static final String URL_PROPERTY = "url";
    public static final String VOLUME_PROPERTY = "volume";
    public static final String YEAR_PROPERTY = "year";
    public static final String REFS_ARTICLES_AUTHORSS_PROPERTY = "refsArticlesAuthorss";
    public static final String REFS_ARTICLES_KEYWORDSS_PROPERTY = "refsArticlesKeywordss";
    public static final String REFS_AUTHORS_FLAT_PROPERTY = "refsAuthorsFlat";
    public static final String REFS_GROUPSS_PROPERTY = "refsGroupss";
    public static final String TO_REFS_ADSNOTES_PROPERTY = "toRefsAdsnotes";
    public static final String TO_REFS_JOURNALS_PROPERTY = "toRefsJournals";

    public static final String ID_ARTICLE_PK_COLUMN = "idArticle";

    public void setIdArticle(Long idArticle) {
        writeProperty(ID_ARTICLE_PROPERTY, idArticle);
    }
    public Long getIdArticle() {
        return (Long)readProperty(ID_ARTICLE_PROPERTY);
    }

    public void setIssue(String issue) {
        writeProperty(ISSUE_PROPERTY, issue);
    }
    public String getIssue() {
        return (String)readProperty(ISSUE_PROPERTY);
    }

    public void setLinkToData(String linkToData) {
        writeProperty(LINK_TO_DATA_PROPERTY, linkToData);
    }
    public String getLinkToData() {
        return (String)readProperty(LINK_TO_DATA_PROPERTY);
    }

    public void setMonth(Short month) {
        writeProperty(MONTH_PROPERTY, month);
    }
    public Short getMonth() {
        return (Short)readProperty(MONTH_PROPERTY);
    }

    public void setPage(String page) {
        writeProperty(PAGE_PROPERTY, page);
    }
    public String getPage() {
        return (String)readProperty(PAGE_PROPERTY);
    }

    public void setStatus(String status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public String getStatus() {
        return (String)readProperty(STATUS_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void setUrl(String url) {
        writeProperty(URL_PROPERTY, url);
    }
    public String getUrl() {
        return (String)readProperty(URL_PROPERTY);
    }

    public void setVolume(String volume) {
        writeProperty(VOLUME_PROPERTY, volume);
    }
    public String getVolume() {
        return (String)readProperty(VOLUME_PROPERTY);
    }

    public void setYear(Long year) {
        writeProperty(YEAR_PROPERTY, year);
    }
    public Long getYear() {
        return (Long)readProperty(YEAR_PROPERTY);
    }

    public void addToRefsArticlesAuthorss(RefsArticlesAuthors obj) {
        addToManyTarget(REFS_ARTICLES_AUTHORSS_PROPERTY, obj, true);
    }
    public void removeFromRefsArticlesAuthorss(RefsArticlesAuthors obj) {
        removeToManyTarget(REFS_ARTICLES_AUTHORSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RefsArticlesAuthors> getRefsArticlesAuthorss() {
        return (List<RefsArticlesAuthors>)readProperty(REFS_ARTICLES_AUTHORSS_PROPERTY);
    }


    public void addToRefsArticlesKeywordss(RefsArticlesKeywords obj) {
        addToManyTarget(REFS_ARTICLES_KEYWORDSS_PROPERTY, obj, true);
    }
    public void removeFromRefsArticlesKeywordss(RefsArticlesKeywords obj) {
        removeToManyTarget(REFS_ARTICLES_KEYWORDSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RefsArticlesKeywords> getRefsArticlesKeywordss() {
        return (List<RefsArticlesKeywords>)readProperty(REFS_ARTICLES_KEYWORDSS_PROPERTY);
    }


    public void addToRefsAuthorsFlat(RefsAuthors obj) {
        addToManyTarget(REFS_AUTHORS_FLAT_PROPERTY, obj, true);
    }
    public void removeFromRefsAuthorsFlat(RefsAuthors obj) {
        removeToManyTarget(REFS_AUTHORS_FLAT_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RefsAuthors> getRefsAuthorsFlat() {
        return (List<RefsAuthors>)readProperty(REFS_AUTHORS_FLAT_PROPERTY);
    }


    public void addToRefsGroupss(RefsGroups obj) {
        addToManyTarget(REFS_GROUPSS_PROPERTY, obj, true);
    }
    public void removeFromRefsGroupss(RefsGroups obj) {
        removeToManyTarget(REFS_GROUPSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RefsGroups> getRefsGroupss() {
        return (List<RefsGroups>)readProperty(REFS_GROUPSS_PROPERTY);
    }


    public void setToRefsAdsnotes(RefsAdsnotes toRefsAdsnotes) {
        setToOneTarget(TO_REFS_ADSNOTES_PROPERTY, toRefsAdsnotes, true);
    }

    public RefsAdsnotes getToRefsAdsnotes() {
        return (RefsAdsnotes)readProperty(TO_REFS_ADSNOTES_PROPERTY);
    }


    public void setToRefsJournals(RefsJournals toRefsJournals) {
        setToOneTarget(TO_REFS_JOURNALS_PROPERTY, toRefsJournals, true);
    }

    public RefsJournals getToRefsJournals() {
        return (RefsJournals)readProperty(TO_REFS_JOURNALS_PROPERTY);
    }


}
