package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.RefsArticles;
import org.vamdc.BasecolTest.dao.RefsAuthors;

/**
 * Class _RefsArticlesAuthors was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RefsArticlesAuthors extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String TO_REFS_ARTICLES_PROPERTY = "toRefsArticles";
    public static final String TO_REFS_AUTHORS_PROPERTY = "toRefsAuthors";

    public static final String ID_PK_COLUMN = "id";

    public void setId(Long id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Long getId() {
        return (Long)readProperty(ID_PROPERTY);
    }

    public void setToRefsArticles(RefsArticles toRefsArticles) {
        setToOneTarget(TO_REFS_ARTICLES_PROPERTY, toRefsArticles, true);
    }

    public RefsArticles getToRefsArticles() {
        return (RefsArticles)readProperty(TO_REFS_ARTICLES_PROPERTY);
    }


    public void setToRefsAuthors(RefsAuthors toRefsAuthors) {
        setToOneTarget(TO_REFS_AUTHORS_PROPERTY, toRefsAuthors, true);
    }

    public RefsAuthors getToRefsAuthors() {
        return (RefsAuthors)readProperty(TO_REFS_AUTHORS_PROPERTY);
    }


}
