package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.RefsKeywords;

/**
 * Class _RefsKeywordsCategories was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RefsKeywordsCategories extends CayenneDataObject {

    public static final String DESIGNATION_PROPERTY = "designation";
    public static final String ID_CATEGORY_PROPERTY = "idCategory";
    public static final String REFS_KEYWORDSS_PROPERTY = "refsKeywordss";

    public static final String ID_CATEGORY_PK_COLUMN = "idCategory";

    public void setDesignation(String designation) {
        writeProperty(DESIGNATION_PROPERTY, designation);
    }
    public String getDesignation() {
        return (String)readProperty(DESIGNATION_PROPERTY);
    }

    public void setIdCategory(Long idCategory) {
        writeProperty(ID_CATEGORY_PROPERTY, idCategory);
    }
    public Long getIdCategory() {
        return (Long)readProperty(ID_CATEGORY_PROPERTY);
    }

    public void addToRefsKeywordss(RefsKeywords obj) {
        addToManyTarget(REFS_KEYWORDSS_PROPERTY, obj, true);
    }
    public void removeFromRefsKeywordss(RefsKeywords obj) {
        removeToManyTarget(REFS_KEYWORDSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RefsKeywords> getRefsKeywordss() {
        return (List<RefsKeywords>)readProperty(REFS_KEYWORDSS_PROPERTY);
    }


}
