package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.CollisionsScientists;

/**
 * Class _Scientists was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Scientists extends CayenneDataObject {

    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String ID_SCIENTIST_PROPERTY = "idScientist";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String COLLISIONS_SCIENTISTSS_PROPERTY = "collisionsScientistss";

    public static final String ID_SCIENTIST_PK_COLUMN = "idScientist";

    public void setFirstName(String firstName) {
        writeProperty(FIRST_NAME_PROPERTY, firstName);
    }
    public String getFirstName() {
        return (String)readProperty(FIRST_NAME_PROPERTY);
    }

    public void setIdScientist(Long idScientist) {
        writeProperty(ID_SCIENTIST_PROPERTY, idScientist);
    }
    public Long getIdScientist() {
        return (Long)readProperty(ID_SCIENTIST_PROPERTY);
    }

    public void setLastName(String lastName) {
        writeProperty(LAST_NAME_PROPERTY, lastName);
    }
    public String getLastName() {
        return (String)readProperty(LAST_NAME_PROPERTY);
    }

    public void addToCollisionsScientistss(CollisionsScientists obj) {
        addToManyTarget(COLLISIONS_SCIENTISTSS_PROPERTY, obj, true);
    }
    public void removeFromCollisionsScientistss(CollisionsScientists obj) {
        removeToManyTarget(COLLISIONS_SCIENTISTSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CollisionsScientists> getCollisionsScientistss() {
        return (List<CollisionsScientists>)readProperty(COLLISIONS_SCIENTISTSS_PROPERTY);
    }


}
