package org.vamdc.basecolTest.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.RefsMatchedData;

/**
 * Class _SpectroDatabases was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpectroDatabases extends CayenneDataObject {

    public static final String ID_SPECTRO_DATABASE_PROPERTY = "idSpectroDatabase";
    public static final String NAME_PROPERTY = "name";
    public static final String REFS_MATCHEDDATAS_PROPERTY = "refsMatcheddatas";

    public static final String ID_SPECTRO_DATABASE_PK_COLUMN = "idSpectroDatabase";

    public void setIdSpectroDatabase(Short idSpectroDatabase) {
        writeProperty(ID_SPECTRO_DATABASE_PROPERTY, idSpectroDatabase);
    }
    public Short getIdSpectroDatabase() {
        return (Short)readProperty(ID_SPECTRO_DATABASE_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToRefsMatcheddatas(RefsMatchedData obj) {
        addToManyTarget(REFS_MATCHEDDATAS_PROPERTY, obj, true);
    }
    public void removeFromRefsMatcheddatas(RefsMatchedData obj) {
        removeToManyTarget(REFS_MATCHEDDATAS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<RefsMatchedData> getRefsMatcheddatas() {
        return (List<RefsMatchedData>)readProperty(REFS_MATCHEDDATAS_PROPERTY);
    }


}
