package org.vamdc.basecolTest.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Elements;
import org.vamdc.BasecolTest.dao.Symmetries;

/**
 * Class _StatusCurrentWorks was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _StatusCurrentWorks extends CayenneDataObject {

    public static final String DETAILS_PROPERTY = "details";
    public static final String GROUP_PROPERTY = "group";
    public static final String GROUP_DETAILS_PROPERTY = "groupDetails";
    public static final String ID_CURRENT_WORK_PROPERTY = "idCurrentWork";
    public static final String TEMPERATURES_PROPERTY = "temperatures";
    public static final String TO_ELEMENTS_PROPERTY = "toElements";
    public static final String TO_ELEMENTS1_PROPERTY = "toElements1";
    public static final String TO_SYMMETRIES_PROPERTY = "toSymmetries";
    public static final String TO_SYMMETRIES1_PROPERTY = "toSymmetries1";

    public static final String ID_CURRENT_WORK_PK_COLUMN = "idCurrentWork";

    public void setDetails(String details) {
        writeProperty(DETAILS_PROPERTY, details);
    }
    public String getDetails() {
        return (String)readProperty(DETAILS_PROPERTY);
    }

    public void setGroup(String group) {
        writeProperty(GROUP_PROPERTY, group);
    }
    public String getGroup() {
        return (String)readProperty(GROUP_PROPERTY);
    }

    public void setGroupDetails(String groupDetails) {
        writeProperty(GROUP_DETAILS_PROPERTY, groupDetails);
    }
    public String getGroupDetails() {
        return (String)readProperty(GROUP_DETAILS_PROPERTY);
    }

    public void setIdCurrentWork(Long idCurrentWork) {
        writeProperty(ID_CURRENT_WORK_PROPERTY, idCurrentWork);
    }
    public Long getIdCurrentWork() {
        return (Long)readProperty(ID_CURRENT_WORK_PROPERTY);
    }

    public void setTemperatures(String temperatures) {
        writeProperty(TEMPERATURES_PROPERTY, temperatures);
    }
    public String getTemperatures() {
        return (String)readProperty(TEMPERATURES_PROPERTY);
    }

    public void setToElements(Elements toElements) {
        setToOneTarget(TO_ELEMENTS_PROPERTY, toElements, true);
    }

    public Elements getToElements() {
        return (Elements)readProperty(TO_ELEMENTS_PROPERTY);
    }


    public void setToElements1(Elements toElements1) {
        setToOneTarget(TO_ELEMENTS1_PROPERTY, toElements1, true);
    }

    public Elements getToElements1() {
        return (Elements)readProperty(TO_ELEMENTS1_PROPERTY);
    }


    public void setToSymmetries(Symmetries toSymmetries) {
        setToOneTarget(TO_SYMMETRIES_PROPERTY, toSymmetries, true);
    }

    public Symmetries getToSymmetries() {
        return (Symmetries)readProperty(TO_SYMMETRIES_PROPERTY);
    }


    public void setToSymmetries1(Symmetries toSymmetries1) {
        setToOneTarget(TO_SYMMETRIES1_PROPERTY, toSymmetries1, true);
    }

    public Symmetries getToSymmetries1() {
        return (Symmetries)readProperty(TO_SYMMETRIES1_PROPERTY);
    }


}
