package org.vamdc.basecolTest.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.BasecolTest.dao.Collisions;

/**
 * Class _StatusAvailables was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _StatusAvailables extends CayenneDataObject {

    public static final String DATE_PROPERTY = "date";
    public static final String ID_COLLISION_PROPERTY = "idCollision";
    public static final String STATUS_PROPERTY = "status";
    public static final String TO_COLLISIONS_PROPERTY = "toCollisions";

    public static final String ID_COLLISION_PK_COLUMN = "idCollision";

    public void setDate(Date date) {
        writeProperty(DATE_PROPERTY, date);
    }
    public Date getDate() {
        return (Date)readProperty(DATE_PROPERTY);
    }

    public void setIdCollision(Long idCollision) {
        writeProperty(ID_COLLISION_PROPERTY, idCollision);
    }
    public Long getIdCollision() {
        return (Long)readProperty(ID_COLLISION_PROPERTY);
    }

    public void setStatus(String status) {
        writeProperty(STATUS_PROPERTY, status);
    }
    public String getStatus() {
        return (String)readProperty(STATUS_PROPERTY);
    }

    public void setToCollisions(Collisions toCollisions) {
        setToOneTarget(TO_COLLISIONS_PROPERTY, toCollisions, true);
    }

    public Collisions getToCollisions() {
        return (Collisions)readProperty(TO_COLLISIONS_PROPERTY);
    }


}
